---
pipelines:
  2018-cisco-devnet-create:
    group: 2018-cisco-devnet-create
    materials:
      github:
        git: https://github.com/joatmon08/2018-cisco-devnet-create.git
    stages:
      - lint:
          jobs:
            lint-python-files:
              tasks:
                - exec:
                    command: flake8
                    arguments:
                      - "."
            lint-yaml-files:
              tasks:
                - exec:
                    command: yamllint
                    arguments:
                      - "."
            check-playbook-syntax:
              tasks:
                - exec:
                    command: make
                    arguments:
                      - "check_ansible_syntax"
      - unit-test:
          jobs:
            unit:
              tasks:
                - exec:
                    command: make
                    arguments:
                      - "unit"
      - contract-test:
          jobs:
            contract:
              tasks:
                - exec:
                    command: make
                    arguments:
                      - "contract"
      - build-and-test:
          jobs:
            test:
              tasks:
                - exec:
                    command: make
                    arguments:
                      - "integration"
