---
pipelines:
  2018-cisco-devnet-create:
    group: 2018-cisco-devnet-create
    materials:
      github:
        git: https://github.com/joatmon08/2018-cisco-devnet-create.git
    stages:
      - lint:
          jobs:
            unit:
              tasks:
                - exec:
                    command: make
                    arguments:
                      - "unit"
